"""
Pytest Test Case and Suite Generator Engine.
Translates parsed API request definitions and translated python assertions
into executable, standard PEP-8 compliant pytest script files, handling edge cases.
"""

import re
import os
import json
import logging
from typing import Dict, Any, List, Optional

logger = logging.getLogger("PytestGenerator")
logger.setLevel(logging.INFO)


class PytestGenerator:
    """
    Core engine responsible for generating standardized, executable Python code structures.
    Creates beautiful, isolated, lint-safe python script configurations.
    """

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir or os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "generated_scripts"
        )
        os.makedirs(self.output_dir, exist_ok=True)
        self.function_name_counts: Dict[str, int] = {}

    def _sanitize_function_name(self, api_name: str, method: str) -> str:
        """
        Transforms arbitrary API names into clean PEP-8 safe python function identifiers,
        resolving name duplication patterns gracefully.
        """
        # Convert to lowercase and swap spaces/special chars to single underscores
        sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", api_name.strip().lower())
        sanitized = re.sub(r"_+", "_", sanitized)
        sanitized = sanitized.strip("_")

        method_prefix = method.lower()
        full_name = f"test_{method_prefix}_{sanitized}"

        # Resolve duplications using unique suffix increments
        if full_name in self.function_name_counts:
            self.function_name_counts[full_name] += 1
            full_name = f"{full_name}_{self.function_name_counts[full_name]}"
        else:
            self.function_name_counts[full_name] = 1

        return full_name

    def compose_script_content(self, api_name: str, method: str, endpoint: str,
                               headers: Dict[str, str], request_body: Optional[str],
                               query_params: Dict[str, str], variables: Dict[str, Any],
                               translated_assertions: str) -> str:
        """
        Synthesizes a standalone PEP-8 Python file comprising mock setups, requests calls,
        parameter injections, variable fallbacks, and standard exception audits.
        """
        func_name = self._sanitize_function_name(api_name, method)
        
        # Format variables block
        var_lines = []
        if variables:
            var_lines.append("    # Resolving collection-level and url dynamic variables")
            for k, v in variables.items():
                val_escaped = json.dumps(v)
                var_lines.append(f"    var_{k.replace('-', '_').replace(' ', '_')} = {val_escaped}")
        
        variables_block = "\n".join(var_lines) if var_lines else "    # No parameter variables mapped"

        # Safe serialization maps
        headers_serialized = json.dumps(headers, indent=8) if headers else "        {}"
        params_serialized = json.dumps(query_params, indent=8) if query_params else "        {}"
        body_serialized = json.dumps(request_body) if request_body else "None"

        # Resolve dynamic variable replacer logic in URLs
        endpoint_parsed = endpoint
        for k in (variables or {}).keys():
            placeholder = f"{{{{{k}}}}}"
            var_ref = f"var_{k.replace('-', '_').replace(' ', '_')}"
            if placeholder in endpoint_parsed:
                endpoint_parsed = endpoint_parsed.replace(placeholder, f"' + str({var_ref}) + '")

        endpoint_string = f"url = '{endpoint_parsed}'"
        # Cleanup potential empty concatenations
        endpoint_string = endpoint_string.replace(" + ''", "").replace("'' + ", "")

        # Format translated assertion lines with correct indentation
        assertion_block_lines = []
        if translated_assertions and translated_assertions.strip():
            for line in translated_assertions.strip().split("\n"):
                if line.strip():
                    assertion_block_lines.append(f"    {line}")
        else:
            assertion_block_lines.append("    assert response.status_code == 200")
        
        assertions_joined = "\n".join(assertion_block_lines)

        # Build output Python Pytest block
        python_content = f"""# -*- coding: utf-8 -*-
\"\"\"
Pytest Automated TestCase for {api_name} ({method})
Autogenerated by Postman Pytest Migrator.
\"\"\"

import pytest
import requests
import json

def {func_name}():
    \"\"\"
    Verifies state and assertions of '{api_name}' REST API.
    Endpoint URL: {method} {endpoint}
    \"\"\"
{variables_block}

    # Prepare HTTP headers
    headers = {headers_serialized.strip()}

    # Prepare Query parameters
    params = {params_serialized.strip()}

    # Prepare request address
    {endpoint_string}

    # Execute request
    try:
        response = requests.request(
            method="{method}",
            url=url,
            headers=headers,
            params=params,
            json={body_serialized},
            timeout=10
        )
    except requests.exceptions.RequestException as e:
        pytest.fail(f"HTTP Connection failed on endpoint execution: {{e}}")

    # Embedded python assertions
{assertions_joined}
"""
        return python_content

    def export_test_file(self, collection_name: str, api_name: str, method: str,
                         script_content: str) -> str:
        """
        Saves the generated python suite file securely onto the filesystem context,
        returning the absolute path of the generated asset file.
        """
        # Form safe file name
        safe_col = re.sub(r"[^a-zA-Z0-9_]", "_", collection_name.lower())
        safe_api = re.sub(r"[^a-zA-Z0-9_]", "_", api_name.lower())
        file_name = f"test_{safe_col}_{safe_api}_{method.lower()}.py"
        
        file_path = os.path.join(self.output_dir, file_name)
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(script_content)
            logger.info(f"Successfully exported Pytest script to filesystem location: {file_path}")
            return file_name
        except IOError as e:
            logger.error(f"Failed to write script code layout to output file path: {e}")
            raise e
